# fly.toml app configuration file generated for ai-auto-posting on 2025-01-13T12:00:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "ai-auto-posting"
primary_region = "lhr"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  FLASK_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "20s"
  interval = "30s"
  method = "GET"
  timeout = "10s"
  path = "/api/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[mounts]
  source = "ai_auto_posting_data"
  destination = "/app/static"
